name: miami_ai_studio
description: Miami AI Hackathon — content generation dashboard

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  flutter_riverpod: ^2.5.1
  video_player: ^2.9.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true